### PR TITLE
redirect to new website

### PR DESCRIPTION
**Pull request by niccokunzmann**
This is a temporary fix: redirect to the github page.
https://github.com/bioPunkKitchen/bioPunkKitchen.github.io/issues/3

### CODE REVIEW

**Comment by speexy** [comment]
@niccokunzmann, the site under https://biopunkkitchen.github.io is not in a publishable state, for several reasons:
- the font is broken
- the logo is in a way to low resolution and should be an svg
- the email signup is broken
- the calendar is empty. debateable whether a calendar is good UX/UI for publishing events, I'd say it is at least bad when there are very few events

**Comment by niccokunzmann** [comment]
Thanks for the feedback.
Please open 4 issues.

**Comment by niccokunzmann** [comment]
You can also work on the code. Your pull request is welcome.

**Comment by niccokunzmann** [comment]
How can we work together?

**Comment by speexy** [comment]
Is the repo going to be on github or are we going to gitlab? (heard björn something about that)
I think it would be best if we create a new branch for new work and then make a pullrequest into master and add someone to review the changes.

**Comment by niccokunzmann** [comment]
> Is the repo going to be on github or are we going to gitlab? (heard
björn something about that)

I think, Björn thinks about many other things than hosting and code
location, so we are free to decide that. I will contribute where ever
the site is. Currently, I see no value in spending my time on moving the
site somewhere else.

> I think it would be best if we create a new branch for new work and
then make a pull request into master and add someone to review the changes.

This way I can learn from you :) Will you do a pull request?
What would you like to work on?

**Comment by speexy** [comment]
I'll clone your repo tomorrow. Today I started off fresh from my gatsby-starter-repo as I thought that your code is on gitlab.

And when I wrapped my head around it, I'll make a PR!

And yes, let's stay on github for now! the cms is hooked up with github anyway.

**Pull request closed without merging**
